
insert into USERS (LOGIN, NAME) values ('user6789', 'Keri Lee');
insert into USERS (LOGIN, NAME) values ('user6001', 'Dollie R. Schnidt');
insert into USERS (LOGIN, NAME) values ('user6002', 'Cornelia J. LeClerc');
insert into USERS (LOGIN, NAME) values ('user6003', 'Cynthia Rau');
insert into USERS (LOGIN, NAME) values ('user6004', 'Douglas R. Cobbs');
insert into USERS (LOGIN, NAME) values ('user6005', 'Michael Patel');
insert into USERS (LOGIN, NAME) values ('user6006', 'Suzanne Wong');
insert into USERS (LOGIN, NAME) values ('user6007', 'Ivan C. Jaya');
insert into USERS (LOGIN, NAME) values ('user6008', 'Ida Ketterer');
insert into USERS (LOGIN, NAME) values ('user6009', 'Laina Ochoa Lucero');
insert into USERS (LOGIN, NAME) values ('user6010', 'Wesley M. Montana');
insert into USERS (LOGIN, NAME) values ('user6011', 'Leslie F. McCleary');
insert into USERS (LOGIN, NAME) values ('user6012', 'Sayeed D. Mudra');
insert into USERS (LOGIN, NAME) values ('user6013', 'Pietronella J. Domingo');
insert into USERS (LOGIN, NAME) values ('user6014', 'John S. O''Leary');
insert into USERS (LOGIN, NAME) values ('user6015', 'Gladys D. Smith');
insert into USERS (LOGIN, NAME) values ('user6016', 'Sally O. Thygesen');
insert into USERS (LOGIN, NAME) values ('user6017', 'Rachel Vogt');
insert into USERS (LOGIN, NAME) values ('user6018', 'Julia DeLong');
insert into USERS (LOGIN, NAME) values ('user6019', 'Mark T. Rizzoli');
insert into USERS (LOGIN, NAME) values ('user6020', 'Maria J. Angelo');
